version: '3.3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - /mnt/efs/gabriel/var/www/html:/var/www/html
    environment:
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: "Endpoint do RDS"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: teste
      WORDPRESS_DB_PASSWORD: teste
      WORDPRESS_TABLE_CONFIG: wp_
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge
